name: documentationtest
on: 
  workflow_call:
      secrets:
        token:
          required: true
jobs:
  call_sphinx_builder:
    uses: rerpha/reusable-workflows/.github/workflows/documentation.yml@main
    with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
