name: documentationtest
on:
  workflow_call:
      inputs:
        config-path:
          required: true
          type: string
      secrets:
        token:
          required: true
jobs:
  call_sphinx_builder:
    runs-on: ubuntu-latest
    steps:
      - uses: rerpha/reusable-workflows/.github/workflows/documentation.yml@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
