name: documentationtest
on:
  workflow_call:
      inputs:
        config-path:
          required: true
          type: string
      secrets:
        token:
          required: true
jobs:
  call_sphinx_builder:
    uses: rerpha/reusable-workflows/.github/workflows/documentation.yml@main
    secrets: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
