name: documentationtest
on: [push, workflow_call]
jobs:
  call_sphinx_builder:
    uses: ISISComputingGroup/reusable-workflows/.github/workflows/sphinx.yml@rerpha-patch-2
    secrets: inherit
    with:
      deploy-branch: "master"

