name: documentationtest
on:
  workflow_call:
    secrets:
      token:
        required: true
  push:
jobs:
  call_sphinx_builder:
    uses: rerpha/reusable-workflows/.github/workflows/documentation.yml@main
    secrets: inherit

